# Generated by Django 5.0.4 on 2024-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
